e = sub.add_parser("collect-evidence", help="Collect standardized IR evidence bundle")
e.add_argument("--incident-id", default=None)
e.add_argument("--minutes", type=int, default=15)
e.add_argument("--app-log-group", default=None)
e.add_argument("--waf-log-group", default=None)
e.add_argument("--ssm-path", default="/lab/db/")
e.add_argument("--secret-id", required=True)
e.add_argument("--out", default="evidence.json")
e.add_argument("--region", default=None)
e.set_defaults(func=cmd_collect_evidence)
